### ISSUE TITLE
feat(bmr): Implement basic header block verification for SNOW

### ISSUE THREAD

**Issue by andrii-kl** [icon-project/icon-bridge#643]
### What needs to be done

Implement simple header block verification for SNOW 

### Why it needs to be done

To make the system more stable

### Other

BSC Verifier's logic present on [this commit](https://github.com/icon-project/icon-bridge/blob/0c840ce14d81e7607be3283623b37532ba25db60/cmd/iconbridge/chain/bsc/receiver.go) can be referenced for header-chain verification.

**Comment by manishbista28** [comment]
I've added base code for header chain verification in the attached branch.
The problem right now is with the comparison of hashes.
As can be seen from the data below (fetched using ethclient's HeaderByNumber method), Header2's parentHash does not match with Header1's Hash.
```
Header1:
 Number: 537975 
 Hash: 0x8acc1e4bffb415b70535699e09c3c238afb267db8cbb8df296025a7bb4236fd4 
 ParentHash: 0x77137fa705a3de2ae84fdb844a08bf8b8fa14eefd28daf621c27b663d68970ba

Header2:
 Number: 537976
 Hash: 0x86b7ab4450c80a47d25121e7697075501b90a9509f97e0d8e0b5f240afe5c821 
 ParentHash: 0x7c99376a4ab36645d05d507e111c0c0acd9f059150675615b9dec4e02b675383

Header3:
 Number: 537977
 Hash: 0xd4c566fdcc5cf19f91638c1dabd21aed5982acaa82c8e4eb8397753329f66d64 
 ParentHash: 0x041baad26be7a3b27bb298cf4ddf1c91e65d47700aa85ec66f6059952d9e51c3
```

A different value for hash is shown by arctic scanner for these blocks.
